### ISSUE TITLE
Avoid duplicated fix guidance

### ISSUE THREAD

**Issue by andresriancho** [vulndb/data#21]
## Task

Think about a solution for duplicated fix guidance texts, which for example are present in these JSON files:
- https://github.com/vulndb/data/blob/master/db/18-form-based-file-upload.json
- https://github.com/vulndb/data/blob/master/db/65-arbitrary-file-upload.json

The solution is, of course, to put all the fix (guidance, effort, etc.) in one place and reference them from the "main" / "vulnerability" json. The details is what we need to think about.
## Solution

Split `json` files in two, one holding the vulnerability information and the other holding the fix.
- Vulnerabilities are stored in `db/vuln/`
- Fixes are stored in `db/fix/`
- Files in fix directory contain:

``` json
{
  "generic": {
    "effort": 50, 
    "guidance": [
      "The first step to remediation is to identify the context in which the ..."
    ]
  }
}
```
- The files in the fix directory have this format: `<id>-<fix-title>.json`
- The vulnerabilities should be changed to point to the fix id:

``` json
  "fix": 321,
```
## Notes
- Using "generic" in fix file to allow us in the future to have different fixes for each language/server (iis/apache/etc)
- The python-sdk should make this process completely 
- An automated process should be able to migrate from current format to the new one
- Manual filtering should allow us to group/remove fixes
## Unittest
- [ ] All "fix" entries in vuln must point to valid json files in the fix directory
- [ ] The unittests that applied to guidance and effort must apply to fix files

**Comment by andresriancho** [comment]
@Zapotek @m0sth8 please review whenever possible

**Comment by Zapotek** [comment]
@andresriancho I like that solution.

**Comment by m0sth8** [comment]
What if we're going to implement some kind of links?
- We have a file `db/fix/123-fix-title.json`
- The vulnerabilities should be changed to point to the fix id:
  `"fix": { "$ref": "#/files/fix/123" }`
- sdk includes `/db/fix/123-fix-title.json` to "fix" field.

In this way we can exclude all repetitive values.

**Comment by andresriancho** [comment]
Loved your idea, :+1:

**Comment by Zapotek** [comment]
+1

**Comment by andresriancho** [comment]
Fixed
