### ISSUE TITLE
Remove duplicated CWE data

### ISSUE THREAD

**Issue by andresriancho** [vulndb/data#36]
While reviewing [the pull request from @robocoder](https://github.com/vulndb/data/pull/34) I noticed that we're duplicating data. The information about which CWE is related to each vulnerability is in two places:

```
   "cwe": ["749"],
   "references": [
     {
       "url": "http://httpd.apache.org/docs/2.2/mod/core.html#limitexcept", 
       "title": "Apache.org"
    },
    {
      "url": "http://cwe.mitre.org/data/definitions/749.html",
      "title": "CWE-749"
```

It doesn't make sense to duplicate this information. If the SDK developer creates a report where he translates the CWE id to a URL and then gets the references he'll get a report with two links to the same URL (http://cwe.mitre.org/data/definitions/749.html in this case)

This was more noticeable at https://github.com/vulndb/data/pull/34 but was a problem before I asked @robocoder to write this PR (sorry for the extra work that won't be merged!)

My proposal to solve this issue is:
- [ ] Do not have any links in the "references" section that point to `cwe.mitre.org`
- [ ] Write a unittest to assert the above rule

**Comment by robocoder** [comment]
I'll take a stab at the unit test when I get home.

**Comment by andresriancho** [comment]
Still needs unittests to make sure we don't make this mistake again
