### ISSUE TITLE
Import arachni scanner data

### ISSUE THREAD

**Issue by andresriancho** [vulndb/data#4]
Arachni has some very interesting data we could use:

https://github.com/Arachni/arachni/blob/master/components/checks/active/file_inclusion.rb
https://github.com/Arachni/arachni/blob/8a7c8cdb2ab00b04a34dc666e3a6607e09b025e2/components/checks/active/xss_event.rb
https://github.com/Arachni/arachni/blob/55f78dbd7d2fc7b53bb7dc5d576662b2810a6b8f/components/checks/active/xss_dom.rb

Agreed with @Zapotek that he'll write a script to export the data out of the arachni tests and into generic JSON files which we can then migrate to the format defined in #5

**Comment by Zapotek** [comment]
Done: e27222af21b0569525718f591eaa2c517d4c1da2
