### ISSUE TITLE
Is this project still alive?

### ISSUE THREAD

**Issue by mdeous** [vulndb/data#44]
The last activity on the repository occured 2 years ago, and since then no new commit was done, nor any issue/pull-request update. So, as I'd like to use this data in a project of mine, I'm wondering if it's worth opening issues and/or submitting pull requests, or if I'd better just fork it and do any change I'd like directly in my fork instead without caring about possibly contributing to this repo.

**Comment by andresriancho** [comment]
Well, I'm here and would be more than happy to receive PR.

**Comment by mdeous** [comment]
Great, I've started working on a [dradis](https://github.com/dradis/dradis-ce) plugin to import vulndb issues directly from a dradis project. I'll be happy to submit PRs once I start using it if anything comes to my mind.

**Comment by andresriancho** [comment]
Awesome, I love dradis
